### ISSUE TITLE
Keep Getting 500 Internal Server Error

### ISSUE THREAD

**Issue by alicansa** [idlesign/deluge-webapi#3]

**Comment by ghost** [comment]
Sorry to necro. Why did you close this? Did you find a way to fix it? Hitting the same problem but literally the entire internet hasn't heard of this problem apparently except for this one post.

**Comment by idlesign** [comment]
@runecasters Consider running deluge in debug mode, a skemming through generated log.
This one was probably related to some Deluge configuration issue rather than _deluge-webapi_.

**Comment by jamesmehorter** [comment]
I ran into this issue and it turned out to be user error on my part. I had only sent the 'Content-Type' header, and overlooked sending the 'Accept' header—both are needed as noted in the documentation: http://deluge-webapi.readthedocs.org/en/latest/quickstart.html#hints

I also was using Postman for my testing—after sending the authentication JSON I would receive the auth cookie and was copy/pasting the cookie _session_id for my subsequent requests, but when I was copying the _session_id a line break caused there to be a space in the middle of the _session_id. 

After fixing those two items I began to receive 200 responses with the expected JSON response from the web api. Hope that helps someone else.
